# Generated by Django 4.0.4 on 2022-05-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('atendente', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FontesDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSolidario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('unidade', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoSolidarioCodigoDeBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.BigIntegerField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.produtosolidario')),
            ],
        ),
        migrations.CreateModel(
            name='ItensAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateField()),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.produtosolidariocodigodebarras')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateField()),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.fontesdoacao')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.produtosolidariocodigodebarras')),
            ],
        ),
    ]
