# Generated by Django 4.0.4 on 2022-06-13 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='id_codigo',
        ),
        migrations.AddField(
            model_name='estoque',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='id_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Mercado.produtosolidario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='quem_cadastrou',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendimentorascunho',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
