# Generated by Django 4.0.4 on 2022-05-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosolidario',
            name='produto',
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='unidade',
            field=models.CharField(max_length=10),
        ),
    ]
