# Generated by Django 4.0.4 on 2022-06-03 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0002_remove_produtosolidario_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('atendente', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodBarProdSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FonteDoacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItensAtendimentoRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateField()),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.fontedoacao')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.codbarprodsol')),
            ],
        ),
        migrations.CreateModel(
            name='ItensAtendimentoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.atendimentotemplate')),
                ('id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.codbarprodsol')),
            ],
        ),
        migrations.RemoveField(
            model_name='produtosolidariocodigodebarras',
            name='id_produto',
        ),
        migrations.RenameField(
            model_name='produtosolidario',
            old_name='preco',
            new_name='preco_solidario',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='fonte',
        ),
        migrations.AddField(
            model_name='itensatendimento',
            name='id_atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.atendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mercado.categoria'),
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='unidade',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='FontesDoacao',
        ),
        migrations.AddField(
            model_name='codbarprodsol',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mercado.produtosolidario'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='id_fonte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Mercado.fontedoacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mercado.codbarprodsol'),
        ),
        migrations.AlterField(
            model_name='itensatendimento',
            name='id_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.codbarprodsol'),
        ),
        migrations.DeleteModel(
            name='ProdutoSolidarioCodigoDeBarras',
        ),
    ]
