# Generated by Django 4.0.4 on 2022-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0002_remove_estoque_id_codigo_estoque_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensatendimentorascunho',
            name='id_produto',
        ),
        migrations.AddField(
            model_name='itensatendimentorascunho',
            name='produto',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
