# Generated by Django 4.0.4 on 2022-06-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0003_remove_itensatendimentorascunho_id_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensatendimentorascunho',
            name='solidarios',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
