# Generated by Django 4.0.4 on 2022-06-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0003_atendimentorascunho_atendimentotemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosolidario',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
