# Generated by Django 4.0.4 on 2022-06-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0004_produtosolidario_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codbarprodsol',
            name='codigo_barras',
            field=models.BigIntegerField(unique=True),
        ),
    ]
