# Generated by Django 4.0.4 on 2022-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0005_itensatendimento_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensatendimento',
            name='solidarios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
