# Generated by Django 4.0.4 on 2022-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0005_alter_codbarprodsol_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosolidario',
            name='max_familia',
            field=models.IntegerField(default=0),
        ),
    ]
