# Generated by Django 4.0.4 on 2022-10-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0006_itensatendimento_solidarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosolidario',
            name='codigo_solidario',
            field=models.CharField(default=' ', max_length=13),
            preserve_default=False,
        ),
    ]
