# Generated by Django 4.0.4 on 2022-10-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0008_estoque_quantidade_saida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='estoque',
            order_with_respect_to='id_produto',
        ),
    ]
