# Generated by Django 4.0.4 on 2022-10-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0009_alter_estoque_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='data',
            new_name='data_atendimento',
        ),
        migrations.AlterOrderWithRespectTo(
            name='estoque',
            order_with_respect_to=None,
        ),
    ]
