# Generated by Django 4.0.4 on 2022-10-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0010_rename_data_atendimento_data_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='data_atendimento',
            new_name='data',
        ),
    ]
