# Generated by Django 4.0.4 on 2023-05-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0013_alter_itensatendimento_id_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['categoria'], 'verbose_name': 'Tipo de Produto', 'verbose_name_plural': 'Tipos de Produto'},
        ),
        migrations.AlterModelOptions(
            name='codbarprodsol',
            options={'ordering': ['id_produto'], 'verbose_name': 'Código do Produto', 'verbose_name_plural': 'Códigos dos Produtos'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['id_produto', 'validade', 'id_fonte'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.AddField(
            model_name='produtosolidario',
            name='essencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='id_fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mercado.fontedoacao', verbose_name='Fonte da Doação'),
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mercado.categoria', verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='quantidade',
            field=models.IntegerField(verbose_name='Peso/Porção/Volume'),
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='unidade',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'Kg'), ('un', 'unidade'), ('sache', 'sache'), ('pct', 'pacote'), ('pctp', 'pacote peq'), ('pctg', 'pacote grande'), ('ml', 'ml'), ('lata', 'lata'), ('l', 'litro'), ('frasco', 'frasco')], max_length=20),
        ),
    ]
