# Generated by Django 4.0.4 on 2023-05-15 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0014_alter_categoria_options_alter_codbarprodsol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoasAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('qtd_pessoas', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('num_solidarios', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('local', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023)])),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo de Produto'),
        ),
        migrations.AlterField(
            model_name='fontedoacao',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
