# Generated by Django 4.0.4 on 2024-04-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0015_pessoasatendimento_alter_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoasatendimento',
            options={'ordering': ['nome'], 'verbose_name': 'Assistido'},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_hora_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_hora_termino',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_assitido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.pessoasatendimento', verbose_name='Assistido'),
        ),
        migrations.AddField(
            model_name='atendimentorascunho',
            name='assitido',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='atendimentorascunho',
            name='data_hora_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentorascunho',
            name='id_assitido',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mercado.pessoasatendimento', verbose_name='Assistido'),
        ),
        migrations.AlterField(
            model_name='produtosolidario',
            name='unidade',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'Kg'), ('un', 'unidade'), ('sache', 'sache'), ('pct', 'pacote'), ('pctp', 'pacote peq'), ('pctg', 'pacote grande'), ('ml', 'ml'), ('lata', 'lata'), ('l', 'litro'), ('frasco', 'frasco'), ('pote', 'pote')], max_length=20),
        ),
    ]
