# Generated by Django 4.0.4 on 2024-04-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0017_rename_id_assitido_atendimento_id_assistido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentorascunho',
            name='assistido',
        ),
    ]
