# Generated by Django 4.0.4 on 2024-06-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0018_remove_atendimentorascunho_assistido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosolidario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
