# Generated by Django 4.1.3 on 2022-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentosMercadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(max_length=50)),
                ('atendente', models.CharField(max_length=50)),
                ('data_atendimento', models.DateField()),
                ('solidarios_inicial', models.IntegerField(default=0)),
                ('preco_produto', models.IntegerField(default=0)),
                ('quantidade', models.IntegerField(default=0)),
                ('registro_atendimento', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
            ],
        ),
    ]
